name: Build and Push Docker Images

on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to go GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build and push auth-service
        uses: docker/build-push-action@v5
        with:
          context: ./services/auth-service
          target: production
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/auth-service:latest

      - name: Build and push product-service
        uses: docker/build-push-action@v5
        with:
          context: ./services/product-service
          target: production
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/product-service:latest

      - name: Build and push order-service
        uses: docker/build-push-action@v5
        with:
          context: ./services/order-service
          target: production
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/order-service:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          target: production
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/frontend-service:latest
